services:
  aeme-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-https://aemesnback-production.up.railway.app/api/v1}
        VITE_KEYCLOAK_URL: ${VITE_KEYCLOAK_URL:-https://keycloak-production-3fda.up.railway.app}
        VITE_KEYCLOAK_REALM: ${VITE_KEYCLOAK_REALM:-aeme}
        VITE_KEYCLOAK_CLIENT_ID: ${VITE_KEYCLOAK_CLIENT_ID:-frontend-aeme}
        VITE_WS_URL: ${VITE_WS_URL:-https://aemesnback-production.up.railway.app/ws}
    ports:
      - "5173:80"
    restart: always
    container_name: aeme-frontend
